### ISSUE TITLE
Width problem on iPhone 6 & 6+

### ISSUE THREAD

**Issue by MikeDyna** [Augustyniak/RATreeView#89] opened 2014-12-17 10:36 UTC
Hi,

first of all, thx for that nice library! Was just what i needed for one part of my current project.

I have very odd behaviour on iPhone 6 & 6+. 
I use cell.accessoryType = UITableViewCellAccessoryCheckmark on my cells and when i show my TreeView the first time, the checkmarks and separators (the cell) are not the width of iPhone 6 & 6+.

But when i start scrolling and cells get reloaded, the checkmark appears on the far right side, where its supposed to be. Still some separators stay at the wrong width.

Would be really nice to get some help on this problem, maybe it´s just my fault.

Here is how i create my RATreeView:

RATreeView *treeView = [[RATreeView alloc] initWithFrame:self.view.bounds];
treeView.delegate = self;
treeView.dataSource = self;
treeView.separatorStyle = RATreeViewCellSeparatorStyleSingleLine;
treeView.rowsExpandingAnimation = RATreeViewRowAnimationFade;
treeView.rowsCollapsingAnimation = RATreeViewRowAnimationFade;

self.treeView = treeView;
[self.containerView insertSubview:treeView atIndex:0];

[self.treeView registerNib:[UINib nibWithNibName:NSStringFromClass([PHTreeViewCell class]) bundle:nil]
        forCellReuseIdentifier:NSStringFromClass([PHTreeViewCell class])];

**Comment by Amr1977** [comment] 2015-11-13 18:25
Any luck with this issue yet ?

**Comment by Augustyniak** [comment] 2015-11-14 20:17
Hey,

I can't reproduce this in iOS 9.1. @Amr1977 which SDK version do you use?

**Comment by Amr1977** [comment] 2015-11-15 08:10
@Augustyniak my issue is solved in https://github.com/Augustyniak/RATreeView/issues/137#issuecomment-156746243

Thank you very much !

**Comment by Augustyniak** [comment] 2015-11-28 14:34
@MikeDyna Sorry for not answering your report for such a long time. Your code looks ok. I hope that changes above fixes the problem and version [v2.0.1](https://github.com/Augustyniak/RATreeView/releases/tag/v2.1.0) works OK.

Closing. Feel free to reopen if necessary.

**Closed by Augustyniak** 2015-11-28 14:34 UTC
Labels: possible UIKit bug
